name: CI

on: [push]

jobs:
  bootloaders:
    name: Bootloaders for both PG1 and PG2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build bootloader image for PG1
        run: ./kas-container build kas-iot2050-boot-pg1.yml
      - name: Build bootloader image for PG2
        run: ./kas-container build kas-iot2050-boot-pg2.yml
      - name: Archive bootloaders
        uses: actions/upload-artifact@v2
        with:
          name: iot2050-bootloaders
          path: build/tmp/deploy/images/iot2050/*.bin
